name: app
description: Flutter puzzle hack challange app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  beamer: ^1.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  mocktail: ^0.2.0

flutter:
  uses-material-design: false
