name: app
description: Flutter puzzle hack challange app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  go_router: ^3.0.3
  material_design_icons_flutter: ^5.0.6595
  url_launcher: ^6.0.20
  material_color_utilities: ^0.1.3
  universal_platform: ^1.0.0
  animations: ^2.0.2

  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

  sixteen_puzzle:
    path: ../sixteen_puzzle

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  mocktail: ^0.2.0

flutter:
  uses-material-design: false

  assets:
    - assets/fonts/

  fonts:
    - family: Oswald
      fonts:
        # - asset: assets/fonts/oswald/Oswald-Thin.ttf
        #   weight: 100
        - asset: assets/fonts/oswald/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/oswald/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/oswald/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/oswald/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/oswald/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/oswald/Oswald-Bold.ttf
          weight: 700
        # - asset: assets/fonts/oswald/Oswald-ExtraBold.ttf
        #   weight: 800
        # - asset: assets/fonts/oswald/Oswald-Black.ttf
        #   weight: 900
